name: My Consultancy Invoices
markdown: kramdown
highlighter: 'null'
encoding: UTF-8
excerpt_separator: ''
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
plugins:
  - jekyll-invoice
post:
  template: _templates/invoice.invoice
editor: vi
# htmltopdf: wkhtmltopdf
